// Community perk-shorthand aliases for search, ported from
// bugrakaan/godroll.tv-app (MIT) — type "kc" to find weapons that can roll
// Kill Clip, "bns pulse" for Bait and Switch pulses, etc.

export const PERK_ALIASES: Record<string, string> = {
  kc: "Kill Clip",
  mkc: "Multikill Clip",
  despo: "Desperado",
  ofa: "One for All",
  swash: "Swashbuckler",
  aj: "Adrenaline Junkie",
  adrenaline: "Adrenaline Junkie",
  fttc: "Fourth Time's the Charm",
  ttc: "Fourth Time's the Charm",
  vorpal: "Vorpal Weapon",
  vw: "Vorpal Weapon",
  fom: "Firing Line",
  fl: "Firing Line",
  bs: "Bait and Switch",
  bns: "Bait and Switch",
  ff: "Feeding Frenzy",
  tt: "Triple Tap",
  rr: "Rewind Rounds",
  rewind: "Rewind Rounds",
  cc: "Clown Cartridge",
  clown: "Clown Cartridge",
  os: "Opening Shot",
  ss: "Snapshot Sights",
  snapshot: "Snapshot Sights",
  qd: "Quickdraw",
  ep: "Explosive Payload",
  tp: "Timed Payload",
  timed: "Timed Payload",
  demo: "Demolitionist",
  destab: "Destabilizing Rounds",
  dr: "Destabilizing Rounds",
  destabilizing: "Destabilizing Rounds",
  inc: "Incandescent",
  volt: "Voltshot",
  vs: "Voltshot",
  chill: "Chill Clip",
  hs: "Headstone",
  df: "Dragonfly",
  hatchling: "Hatchling",
  rf: "Rangefinder",
  eots: "Eye of the Storm",
  eye: "Eye of the Storm",
  zm: "Zen Moment",
  zen: "Zen Moment",
  mt: "Moving Target",
  mtt: "Moving Target",
  moving: "Moving Target",
  slide: "Slideshot",
  sw: "Slideways",
  ab: "Arrowhead Brake",
  arrowhead: "Arrowhead Brake",
  hf: "Hammer-Forged Rifling",
  hammer: "Hammer-Forged Rifling",
  sb: "Smallbore",
  fb: "Full Bore",
  fullbore: "Full Bore",
  cr: "Corkscrew Rifling",
  corkscrew: "Corkscrew Rifling",
  fluted: "Fluted Barrel",
  pr: "Polygonal Rifling",
  polygonal: "Polygonal Rifling",
  eb: "Extended Barrel",
  extbarrel: "Extended Barrel",
  chambered: "Chambered Compensator",
  tac: "Tactical Mag",
  tacmag: "Tactical Mag",
  tm: "Tactical Mag",
  am: "Appended Mag",
  appended: "Appended Mag",
  em: "Extended Mag",
  extmag: "Extended Mag",
  fm: "Flared Magwell",
  flared: "Flared Magwell",
  rico: "Ricochet Rounds",
  ricochet: "Ricochet Rounds",
  hcr: "High-Caliber Rounds",
  hir: "High-Impact Reserves",
  alloy: "Alloy Magazine",
  apr: "Armor-Piercing Rounds",
  armor: "Armor-Piercing Rounds",
  lm: "Light Mag",
  light: "Light Mag",
  acc: "Accurized Rounds",
  accurized: "Accurized Rounds",
  sr: "Steady Rounds",
  steady: "Steady Rounds",
  sub: "Subsistence",
  recon: "Reconstruction",
  ea: "Envious Arsenal",
  envious: "Envious Arsenal",
  sfa: "Stats for All",
  stats: "Stats for All",
  aa: "Ambitious Assassin",
  ambitious: "Ambitious Assassin",
  pm: "Perpetual Motion",
  perpetual: "Perpetual Motion",
  td: "Threat Detector",
  threat: "Threat Detector",
  alh: "Auto-Loading Holster",
  el: "Explosive Light",
  ka: "Keep Away",
  pi: "Precision Instrument",
};

export const TYPE_ALIASES: Record<string, string> = {
  smg: "submachine gun",
  hc: "hand cannon",
  ar: "auto rifle",
  gl: "grenade launcher",
  rl: "rocket launcher",
  mg: "machine gun",
  lmg: "machine gun",
  lfr: "linear fusion rifle",
  fr: "fusion rifle",
  bow: "combat bow",
  sniper: "sniper rifle",
  shotty: "shotgun",
  pulse: "pulse rifle",
  scout: "scout rifle",
  trace: "trace rifle",
};

/**
 * True when `token` matches this weapon: substring of its name/type, a
 * weapon-type alias ("smg"), or a perk in its pool (directly or via a
 * community alias like "kc").
 */
export function tokenMatchesWeapon(
  token: string,
  weaponName: string,
  weaponType: string,
  perkNames: string,
): boolean {
  const t = token.toLowerCase();
  if (weaponName.includes(t) || weaponType.includes(t)) return true;
  const typeAlias = TYPE_ALIASES[t];
  if (typeAlias !== undefined && weaponType.includes(typeAlias)) return true;
  if (perkNames.includes(t)) return true;
  const alias = PERK_ALIASES[t];
  return alias !== undefined && perkNames.includes(alias.toLowerCase());
}
